# Test build for each PR
name: Build with tests

on:
    pull_request:
        branches: [main]
    schedule:
      - cron:  '0 0 * * *'

jobs:
    test_build_ubuntu:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 12
            - name: Install java 11
              uses: actions/setup-java@v1
              with:
                java-version: "11"
            - name: Download ballerina distribution
              uses: wei/wget@v1
              with:
                args: http://dist-dev.ballerina.io/downloads/swan-lake-alpha4/ballerina-swan-lake-alpha4.zip
            - run: mkdir extractedDistribution
            - name: Unzip ballerina distribution
              uses: TonyBogdanov/zip@1.0
              with:
                args: unzip -qq ./ballerina-swan-lake-alpha4.zip -d ./extractedDistribution
            - run: rm ballerina-swan-lake-alpha4.zip
            - run: npm ci
            - name: Build plugin with tests
              uses: GabrielBB/xvfb-action@v1.0
              with:
                run: ./gradlew clean build

    build_windows:
      runs-on: windows-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Setup node
          uses: actions/setup-node@v1
          with:
            node-version: 12
        - name: Install java 11
          uses: actions/setup-java@v1
          with:
            java-version: "11"
        - run: mkdir extractedDistribution
        - name: Download Ballerina distribution
          run: Invoke-WebRequest -Uri http://dist-dev.ballerina.io/downloads/swan-lake-alpha4/ballerina-swan-lake-alpha4.zip -OutFile extractedDistribution\ballerina-swan-lake-alpha4.zip
        - name: Unzip Ballerina distribution
          run: Expand-Archive -LiteralPath extractedDistribution\ballerina-swan-lake-alpha4.zip -DestinationPath extractedDistribution\
        - run: rm extractedDistribution\ballerina-swan-lake-alpha4.zip
        - run: npm ci -f
        - name: Build plugin with tests
          uses: GabrielBB/xvfb-action@v1.0
          with:
            run: ./gradlew clean build -x test
